services:
  clean-ddd-mysql:
    container_name: clean-ddd-mysql
    platform: linux/x86_64
    image: mysql:8
    environment:
      MYSQL_DATABASE: clean_ddd
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
      - "33071:3306"
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d  
    networks:
      - clean-ddd-network

  clean-ddd-phpmyadmin:
    container_name: clean-ddd-phpmyadmin
    platform: linux/x86_64
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=clean-ddd-mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - 18081:80
    depends_on:
      - clean-ddd-mysql
    networks:
      - clean-ddd-network

networks:
  clean-ddd-network:
    name: clean_ddd__network
